<div class="inner">
  <div class="inner-subtitle">
    <p>公告及登入系統</p>
    <p>Dorm Information</p>
  </div>
  <div class="inner-content">
    <a href="/?inner=login">login</a>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit molestiae eveniet numquam excepturi sunt tenetur officia ducimus optio aliquid voluptas ea vero qui velit alias voluptate aut obcaecati animi quam eos nobis, perferendis dicta magnam rem dolorum. Ullam magni laborum quod placeat maiores eos vero molestias nemo possimus optio voluptas at nostrum illum facere laudantium eveniet velit tenetur sit id error fugit, vitae, beatae assumenda. Ab, fugit consequuntur beatae deserunt explicabo enim vitae dolorem officiis, reprehenderit, quidem aspernatur. Laborum doloremque distinctio animi tempora nisi minus? Sit quidem, vel eos voluptates eligendi nisi reprehenderit architecto doloribus non quibusdam cupiditate minima numquam.</p>
  </div>
</div>